### ISSUE TITLE
TypeError: 'stopPropagation' called on an object that does not implement interface Event 

### ISSUE THREAD

**Issue by vj--** [vimperator/vimperator-labs#582]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:  3.14.0 (created: 2016/06/07 23:58:16)
Firefox:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:48.0) Gecko/20100101 Firefox/48.0
```

##### Description:

Clean install of vimperator from add-ons website of Firefox is not working as expected. The profile is also cleared. 

- 'f' is not showing hints to follow
- unable to enter text within textfields

Following error shows up though, not sure the above is related to this...

TypeError: 'stopPropagation' called on an object that does not implement interface Event 

##### Expected behavior:

Should be able to follow hints and enter text into textfields

##### Steps to reproduce:

In this case, I had a previous vimperator installed with Firefox. Did a clean (profile and vimperator uninstall) and reinstalled.

**Comment by davehouse** [comment]
I see the same error in Nightly and Developer, but not in current standard Firefox, 48.0.2. I tested back through Vimperator 3.12 and see the same error.

**Comment by davehouse** [comment]
It looks like it is an issue with running Vimperator and e10s, multi-process Firefox. You can turn off multi-process (on by default in Developer and Nightly). See https://github.com/vimperator/vimperator-labs/issues/211 and others.

**Comment by spellingmistake** [comment]
@davehouse I tried to disable multi-process support in FF _53.0a2_ using _about:config_ -> _browser.tabs.remote.autostart_ but to no avail. The error message does not vanish!

**Comment by davehouse** [comment]
@spellingmistake I see a failure now also when I updated my firefox dev edition to 53.0a2. The new error I see when I try to use the "f" link highlights or search is:
```
DereferenceError: tabs is not defined
```

You can confirm that your firefox is not using multi-process/e10s on the about:support page, "Multiprocess Windows" will say something like, "0/1 (Disabled)". And the about:preferences page will show an un-checked checkbox for "Enable multi-process Firefox ...".

So, with the new failure, disabling multiprocess is not allowing Vimperator to work correctly in Firefox 53 :(

**Comment by davehouse** [comment]
I think this converges with issue #568 now as that reports the "ReferenceError: tabs is not defined" error.

**Comment by marcusmueller** [comment]
This issue does also appear with clean installations of Firefox on Fedora 26 (version 54 at the time of writing). Thus, on current Fedora, vimperator is unusable.
