### ISSUE TITLE
Vimperator doesn't work in Firefox 34.0.5

### ISSUE THREAD

**Issue by basvdheuvel** [vimperator/vimperator-labs#110]
Today I upgraded my Firefox to version 34.0.5. It starts fine, but as soon as I try to scroll using 'j' the following message is display: `TypeError: ['@@iterator'] is not a function`.
