### ISSUE TITLE
TypeError: ['@@iterator'] is not a function 

### ISSUE THREAD

**Issue by yograf** [vimperator/vimperator-labs#118]
Am I the only one who got this.
Start to show after updating firefox to 34.0.5
