### ISSUE TITLE
Various problems on Firefox Developer Edition on OS X Maverick

### ISSUE THREAD

**Issue by pm5** [vimperator/vimperator-labs#176]
Mine is version 37.0a now.  This browser updates roughly everyday.  Around a dozen versions ago,

* Follow hints stopped working.  An error message "Error: elem.id.quote is not a function" appeared on the status bar when I pressed `f`.
* When I pressed `o`, page history display is broken.  A screenshot is attached.

![screen shot 2015-02-09 at 8 31 04](https://cloud.githubusercontent.com/assets/119645/6106252/b00ea13c-b09a-11e4-92d6-9e73ee0f25ca.png)

**Comment by Alcesmire** [comment]
I can confirm this. Also, `f<esc>` gets me:
```
ReferenceError: styles is not defined                     hints.js:551:8
TypeError: this._tabNavigation[firstHint] is undefined    hints.js:449:8
```
in addition to the
```
TypeError: elem.id.quote is not a function
```
already reported.

**Comment by timss** [comment]
Tried with a fresh install of Firefox Developer Edition 37.0a2 with Vimperator 3.8.3-a5. I'm not seeing any of the errors reported here. For the record I did open maybe 20 or so different websites so there was a little history, but not much. 

- Which version of Vimperator are you using? 
- Could it be that there's some leftovers from previous installs that could be solved by reinstall?

It's working fine with a regular build of Firefox 37.0a2 (Iceweasel on Linux) aswell, which is not a new install.

**Comment by gkatsev** [comment]
Yeah, the current alpha release (3.8.3-a5) does fix a lot of these issues.
Stay tuned, an official release for AMO is forthcoming.

**Comment by Alcesmire** [comment]
I swear I installed the current alpha before to solve this problem. Maybe Firefox considered the firefox "repo" version to be newer and "updated" it. Is it advisable to remove the one in the repo before installing the alpha?

In any case, the alpha does indeed solve all issues mentioned here.

**Comment by timss** [comment]
Correct, Firefox will try to update it even if the alpha is newer.

**Comment by gkatsev** [comment]
Yes, if you uninstall your original vimperator and then install the XPI from github, you should be ok.

**Comment by pm5** [comment]
I reinstalled the XPI from github, and the problems are gone.  Thanks for the help!

**Comment by sukima** [comment]
Is there anyway to force the alpha version. Every day (sometimes twice a day) FF developer edition updates (or crashes) and when it does vimperator reverts back to an older version forcing me to go to github and reinstall the alpha XPI. This is getting really annoying to do this constantly. Why can't the install of the alpha XPI be permanent?

**Comment by sukima** [comment]
Ahh, auto updates keeps thinking 3.8.3 is higher then 3.8.3-a5. Tell everyone you have to turn off auto updates! (What a pain in the .....).

**Comment by gkatsev** [comment]
Uninstalling AMO vimperator and the installing this XPI, seemed to fix the issue, but yeah, totally makes sense that it's autoupdates.
