### ISSUE TITLE
Errror on start, and with moveto

### ISSUE THREAD

**Issue by karinlag** [vimperator/vimperator-labs#482]
##### Issue type:

- Bug report

##### Version: 

```
1.3.1.1-let-fixed

:version gives me SyntaxError: attr2

```

##### Description:

1. when I start Thunderbird, I get:

TypeError: array(......). flatten is not a function

2. :s (aka moveto) does not do any searching of directories when I start typing in something.

##### Expected behavior:

1. I didn't expect to get an error on start

2. I expect muttator to give me directories that I can tab-select for moving things.

##### Steps to reproduce:

I am on windows 7, with Thunderbird 45 downloaded and installed on the 19th of April this year.

I downloaded 1.3.1.1-let-fixed from the add-ons website.

**Comment by timss** [comment]
@karinlag Did #485 possibly fix this?

**Comment by gineadai** [comment]
@timss Yes. But now on startup appear - `TyperError: ervices.get(...)defaultServer is null` -   probably okay and dissapear after pressing ESC, but error `TypeError: gDBView is null` constantly in commandline. How to fix this?

**Comment by stepshal** [comment]
@tmss Yes. Thunderbird 45.1 version, Muttator version current from git. Those problems not occur.

**Comment by stepshal** [comment]
But moveto not working in 50.0a1.

**Comment by karinlag** [comment]
Any movement on getting a working xpi? I am on the verge of abandoning TB altogether...

**Comment by webmagnets** [comment]
+1

**Comment by timss** [comment]
Please see https://github.com/vimperator/vimperator-labs/issues/617#issuecomment-255235354
